version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: 'drives-postgres'
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    restart: 'unless-stopped'

  adminer:
    image: adminer:latest
    container_name: 'drives-adminer'
    ports:
    - "8080:8080/tcp"
    depends_on:
      postgres:
        condition: service_healthy
    restart: 'unless-stopped'


  app:
    container_name: 'drives-app'
    build: './'
    image: rehanone/drives
    ports:
    - "5000:5000/tcp"
    environment:
      DATABASE_DIALECT: postgres
      DATABASE_HOST: postgres
      DATABASE_NAME: ${DB_DATABASE}
      DATABASE_USERNAME: ${DB_USERNAME}
      DATABASE_PASSWORD: ${DB_PASSWORD}
      PORT: 5000
    depends_on:
      postgres:
        condition: service_healthy
    restart: 'unless-stopped'

volumes:
  postgres_data: