version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: 'drives-postgres'
    ports:
    - "5432:5432/tcp"
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    restart: 'unless-stopped'

  adminer:
    image: adminer:latest
    container_name: 'drives-adminer'
    ports:
    - "8080:8080/tcp"
    depends_on:
      postgres:
        condition: service_healthy
    restart: 'unless-stopped'


  app:
    container_name: 'drives-app'
    build: './'
    image: rehanone/drives
    ports:
    - "5000:5000/tcp"
    environment:
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_DIALECT: ${DATABASE_DIALECT}
      DATABASE_HOST: postgres
      PORT: 5000
    depends_on:
      postgres:
        condition: service_healthy
    restart: 'unless-stopped'

volumes:
  postgres_data: